slug = "power-function"

refill = 7200 # 2 hours

[information.en]
title = "Power function"
instructions_file = "instructions_en.md"

[evaluator]
docker_image = "python:latest"
# simplest case, no run or test commands
grade_command = "python -m grading.tests"

[files]
visible = [
  "task/script.py",
]
editable = [
  "task/script.py",
]
grading = [
  "grading/tests.py",
]
solution = [
  "solution/script.py",
]

