slug = "power-function"
type = "example"

# compared to regular assignments, lecture examples differ as follows:
# - test and run are both optional, only grade is compulsory
# - an additional field type = "example" indicates that this is an example

max_attempts = 1
refill = 20 # 20 seconds
max_points = 1

[information.en]
title = "Power function"
instructions_file = "instructions_en.md"

[evaluator]
docker_image = "python:latest"
#run_command = "python task/script.py"
#test_command = "python -m unittest discover -v task"
grade_command = "python -m grading.tests"

[files]
visible = [
  "task/script.py",
]
editable = [
  "task/script.py",
]
grading = [
  "grading/tests.py",
]
solution = [
  "solution/script.py",
]

