slug = "string_manipulation"


max_attempts = 6
refill = 43200 # 12 hours
max_points = 2

[information.en]
title = "String Manipulation in Python"
instructions_file = "instructions_en.md"

[evaluator]
docker_image = "python:latest"
run_command = "python -m task.script"
test_command = "python -m unittest discover -v task"
grade_command = "python -m grading.tests"

[llm]
submission = "task/explanation.md"
rubrics = 'rubrics/rubrics.toml'
examples = 'grading/examples.toml'
solution = 'solution/explanation.md'
cot = true
voting = 3
post = "grading/post.md"
temperature = 0.2 # Decides the randomness of the gpt model
model = "gpt" # gpt or claude

[files]
visible = [
  "task/script.py",
  "task/explanation.md",
  "task/tests.py",
]
editable = [
  "task/script.py",
  "task/explanation.md",
]
grading = [
  "grading/tests.py",
]
solution = [
  "solution/script.py",
  "solution/explanation.md",
]