slug = "pass-by-reference"

refill = 7200 # 2 hours

[information.en]
title = "Pass-by-reference"
instructions_file = "instructions_en.md"

[evaluator]
docker_image = "python:latest"
grade_command = "python -m grading.tests"

[files]
visible = [
  "task/answer.txt",
]
editable = [
  "task/answer.txt",
]
grading = [
  "grading/tests.py",
]
solution = [
  "solution/answer.txt",
]

