slug = "circle-square-rect"

refill = 7200 # 2 hours

[information.en]
title = "Circle, Square, Rectangle"
instructions_file = "instructions_en.md"

[evaluator]
docker_image = "python:latest"
# run and test commands are optional but allowed for examples
run_command = "python task/script.py"
test_command = "python -m unittest discover -v task"
grade_command = "python -m grading.tests"

[files]
visible = [
  "task/script.py",
  "task/tests.py",
]
editable = [
  "task/script.py",
  "task/tests.py",
]
grading = [
  "grading/tests.py",
]
solution = [
  "solution/script.py",
]

